# Generated by Django 4.2.4 on 2023-08-31 12:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('time_alloted', models.IntegerField(default=0)),
                ('link', models.SlugField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Creation',
                'verbose_name_plural': 'Event Creations',
                'ordering': ['start_time'],
            },
        ),
    ]
