# Generated by Django 4.2.4 on 2023-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_eventcreation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcreation',
            name='booked_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventcreation',
            name='total_slots',
            field=models.IntegerField(default=0),
        ),
    ]
